target:
  helmChartPath: helm
  helmValuesPath: helm/values.yaml


advisors:
   except:
   - pod_security_policies_advisor
   - readiness_probe_advisor 
   
   
#   except:
#   - pod_security_policies_advisor
#   - readiness_probe_advisor




