apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "hello-world-ui.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "hello-world-ui.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
