apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
    owner: ahmed
  name: liveness-exec
spec:
  containers:
  - name: test-container
    image: ubuntu:16.0.4
    args:
    - /bin/sh
    - ls
    livenessProbe:
      exec:
        command:
        - ls
      initialDelaySeconds: 5
      periodSeconds: 5
    
    readinessProbe:
      exec:
        command:
        - ls
      initialDelaySeconds: 5
      periodSeconds: 5
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
          - NET_BIND_SERVICE
        drop:
          - ALL
      privileged: false
      procMount: Default
      readOnlyRootFilesystem: false
      runAsGroup: 1000
      runAsUser: 1000
      seLinuxOptions:
        level: s0:c123,c456