
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1-a
  labels:
    app: deployment-1-a
spec:
  selector:
    matchLabels:
      app: deployment-1-a
  template:
    metadata:
      labels:
        app: deployment-1-a
    spec:
      containers:
      - name: deployment-1-a-container
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c", "sleep 1d"]


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1-b
  labels:
    app: deployment-1-b
spec:
  selector:
    matchLabels:
      app: deployment-1-b
  template:
    metadata:
      labels:
        app: deployment-1-b
    spec:
      containers:
      - name: deployment-1-b-container
        image: ubuntu
        command: ["/bin/bash"]
        args: ["-c", "sleep 1d"]
        securityContext:
          privileged: true

