name: hello-world-ui
version: 0.2
description: Hello world sample UI to demonstrate deployment capabilities
keywords:
  - alfresco
  - anaxes
  - hello
  - world
home: https://github.com/Alfresco/alfresco-anaxes-hello-world
sources:
  - https://github.com/Alfresco/alfresco-anaxes-hello-world-ui-deployment/helm
maintainers:
  - name: Alfresco
