name: Build

on:
  push:
    branches: [ master, compliance ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Magalix
        uses: ahsayde/test-action@main
        with:
          webhook: "https://console.gcp.dev.magalix.com/api/v1/kubeguard/5e95e8e3-c411-429e-8c50-2fa9a3806a21/cb1d451b-16e0-4df6-add0-5c4d7ff25e68"
          directory: compliance
