name: magalix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  magalix-kube-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Magalix
        uses: magalixcorp/magalix-action@v0.0.1
        with:
          webhook: ${{ secrets.MAGALIX_GUARD }}


