name: Magalix

on:
  push:
    branches: [ master, magalix-action ]
  pull_request:
    branches: [ master, magalix-action ]

jobs:
  magalix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Magalix
      uses: magalixcorp/magalix-action@dev
      with:
        webhook: ${{ secrets.GUARD_WEBHOOK }}
